/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface LogDbInterface extends ethers.utils.Interface {
  functions: {
    "storeData(string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "storeData", values: [string]): string;

  decodeFunctionResult(functionFragment: "storeData", data: BytesLike): Result;

  events: {
    "DataEvent(address,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DataEvent"): EventFragment;
}

export type DataEventEvent = TypedEvent<
  [string, string],
  { sender: string; data: string }
>;

export type DataEventEventFilter = TypedEventFilter<DataEventEvent>;

export interface LogDb extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LogDbInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    storeData(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  storeData(
    data: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    storeData(data: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "DataEvent(address,string)"(
      sender?: string | null,
      data?: null
    ): DataEventEventFilter;
    DataEvent(sender?: string | null, data?: null): DataEventEventFilter;
  };

  estimateGas: {
    storeData(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    storeData(
      data: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
